/**
 * Centralized watermark text helper. Use across PDF/image exports so all
 * premium artifacts carry consistent "Generated for {name} — OverraPrep AI".
 */
export function buildWatermark(opts: { fullName?: string | null; suffix?: string }) {
  const name = opts.fullName?.trim();
  const suffix = opts.suffix || "OverraPrep AI";
  return name ? `Generated for ${name} — ${suffix}` : `Generated by ${suffix}`;
}

/** Apply a diagonal watermark to every page of an open jsPDF doc. */
export function applyPdfWatermark(doc: any, text: string) {
  try {
    const total = doc.getNumberOfPages?.() ?? 1;
    for (let i = 1; i <= total; i++) {
      doc.setPage(i);
      const w = doc.internal.pageSize.getWidth();
      const h = doc.internal.pageSize.getHeight();
      doc.saveGraphicsState?.();
      doc.setGState?.(new doc.GState({ opacity: 0.08 }));
      doc.setTextColor(180, 140, 40);
      doc.setFontSize(36);
      doc.text(text, w / 2, h / 2, { align: "center", angle: -30 });
      doc.restoreGraphicsState?.();
      // Visible footer line
      doc.setTextColor(150);
      doc.setFontSize(8);
      doc.text(text, w / 2, h - 6, { align: "center" });
    }
  } catch { /* swallow — watermark must never break export */ }
}