import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { Users, Copy, LogOut, UserPlus, Crown } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

interface Team {
  id: string;
  name: string;
  code: string;
  description: string | null;
  created_by: string;
  max_members: number;
}

interface TeamMember {
  user_id: string;
  profile?: {
    full_name: string | null;
    email: string;
  };
}

export const TeamCard = () => {
  const { user } = useAuth();
  const [team, setTeam] = useState<Team | null>(null);
  const [members, setMembers] = useState<TeamMember[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [joinDialogOpen, setJoinDialogOpen] = useState(false);
  const [newTeamName, setNewTeamName] = useState("");
  const [newTeamDescription, setNewTeamDescription] = useState("");
  const [joinCode, setJoinCode] = useState("");

  useEffect(() => {
    if (user) {
      fetchUserTeam();
    }
  }, [user]);

  const fetchUserTeam = async () => {
    if (!user) return;
    
    try {
      // Check if user is in a team
      const { data: membership, error: memberError } = await supabase
        .from("team_members")
        .select("team_id")
        .eq("user_id", user.id)
        .maybeSingle();

      if (memberError) throw memberError;

      if (membership) {
        // Fetch team details
        const { data: teamData, error: teamError } = await supabase
          .from("teams")
          .select("*")
          .eq("id", membership.team_id)
          .single();

        if (teamError) throw teamError;
        setTeam(teamData);

        // Fetch team members with profiles
        const { data: membersData, error: membersError } = await supabase
          .from("team_members")
          .select("user_id")
          .eq("team_id", membership.team_id);

        if (membersError) throw membersError;

        // Fetch profiles for members
        const memberIds = membersData.map(m => m.user_id);
        const { data: profiles, error: profilesError } = await supabase
          .from("profiles")
          .select("id, full_name, email")
          .in("id", memberIds);

        if (profilesError) throw profilesError;

        const enrichedMembers = membersData.map(m => ({
          ...m,
          profile: profiles?.find(p => p.id === m.user_id)
        }));

        setMembers(enrichedMembers);
      }
    } catch (error) {
      console.error("Error fetching team:", error);
    } finally {
      setLoading(false);
    }
  };

  const createTeam = async () => {
    if (!user || !newTeamName.trim()) return;

    try {
      const { error } = await supabase.from("teams").insert({
        name: newTeamName.trim(),
        description: newTeamDescription.trim() || null,
        created_by: user.id,
        code: "" // Will be auto-generated by trigger
      });

      if (error) throw error;

      toast.success("Team created successfully!");
      setCreateDialogOpen(false);
      setNewTeamName("");
      setNewTeamDescription("");
      fetchUserTeam();
    } catch (error: any) {
      toast.error(error.message || "Failed to create team");
    }
  };

  const joinTeam = async () => {
    if (!user || !joinCode.trim()) return;

    try {
      // Find team by code
      const { data: teamData, error: teamError } = await supabase
        .from("teams")
        .select("id, max_members")
        .eq("code", joinCode.trim().toUpperCase())
        .maybeSingle();

      if (teamError) throw teamError;
      if (!teamData) {
        toast.error("Team not found with this code");
        return;
      }

      // Check member count
      const { count, error: countError } = await supabase
        .from("team_members")
        .select("*", { count: "exact", head: true })
        .eq("team_id", teamData.id);

      if (countError) throw countError;
      if (count && count >= teamData.max_members) {
        toast.error("This team is full");
        return;
      }

      // Join team
      const { error: joinError } = await supabase.from("team_members").insert({
        team_id: teamData.id,
        user_id: user.id
      });

      if (joinError) {
        if (joinError.code === "23505") {
          toast.error("You're already in a team. Leave your current team first.");
        } else {
          throw joinError;
        }
        return;
      }

      toast.success("Joined team successfully!");
      setJoinDialogOpen(false);
      setJoinCode("");
      fetchUserTeam();
    } catch (error: any) {
      toast.error(error.message || "Failed to join team");
    }
  };

  const leaveTeam = async () => {
    if (!user || !team) return;

    try {
      const { error } = await supabase
        .from("team_members")
        .delete()
        .eq("user_id", user.id)
        .eq("team_id", team.id);

      if (error) throw error;

      // If creator left, delete the team
      if (team.created_by === user.id) {
        await supabase.from("teams").delete().eq("id", team.id);
        toast.success("Team disbanded");
      } else {
        toast.success("Left team successfully");
      }

      setTeam(null);
      setMembers([]);
    } catch (error: any) {
      toast.error(error.message || "Failed to leave team");
    }
  };

  const copyCode = () => {
    if (team?.code) {
      navigator.clipboard.writeText(team.code);
      toast.success("Team code copied!");
    }
  };

  if (loading) {
    return (
      <Card className="bg-card border-border">
        <CardContent className="p-6">
          <div className="animate-pulse space-y-3">
            <div className="h-4 bg-muted rounded w-1/2" />
            <div className="h-4 bg-muted rounded w-3/4" />
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!team) {
    return (
      <Card className="bg-card border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Users className="w-5 h-5 text-primary" />
            Team Competition
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Join or create a team to compete on the team leaderboards!
          </p>
          <div className="flex gap-2">
            <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="default" size="sm">
                  <Users className="w-4 h-4 mr-2" />
                  Create Team
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create a Team</DialogTitle>
                </DialogHeader>
                <div className="space-y-4 pt-4">
                  <div className="space-y-2">
                    <Label htmlFor="team-name">Team Name</Label>
                    <Input
                      id="team-name"
                      value={newTeamName}
                      onChange={(e) => setNewTeamName(e.target.value)}
                      placeholder="Enter team name"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="team-description">Description (optional)</Label>
                    <Input
                      id="team-description"
                      value={newTeamDescription}
                      onChange={(e) => setNewTeamDescription(e.target.value)}
                      placeholder="Enter team description"
                    />
                  </div>
                  <Button onClick={createTeam} className="w-full" disabled={!newTeamName.trim()}>
                    Create Team
                  </Button>
                </div>
              </DialogContent>
            </Dialog>

            <Dialog open={joinDialogOpen} onOpenChange={setJoinDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" size="sm">
                  <UserPlus className="w-4 h-4 mr-2" />
                  Join Team
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Join a Team</DialogTitle>
                </DialogHeader>
                <div className="space-y-4 pt-4">
                  <div className="space-y-2">
                    <Label htmlFor="join-code">Team Code</Label>
                    <Input
                      id="join-code"
                      value={joinCode}
                      onChange={(e) => setJoinCode(e.target.value)}
                      placeholder="Enter team code (e.g., TEAM-XXXXX)"
                    />
                  </div>
                  <Button onClick={joinTeam} className="w-full" disabled={!joinCode.trim()}>
                    Join Team
                  </Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="bg-card border-border">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-lg">
            <Users className="w-5 h-5 text-primary" />
            {team.name}
          </div>
          <Button variant="ghost" size="sm" onClick={copyCode} className="text-xs">
            <Copy className="w-3 h-3 mr-1" />
            {team.code}
          </Button>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {team.description && (
          <p className="text-sm text-muted-foreground">{team.description}</p>
        )}
        
        <div className="space-y-2">
          <p className="text-sm font-medium">Members ({members.length}/{team.max_members})</p>
          <div className="space-y-1">
            {members.map((member) => (
              <div
                key={member.user_id}
                className="flex items-center gap-2 text-sm p-2 rounded-lg bg-muted/50"
              >
                {member.user_id === team.created_by && (
                  <Crown className="w-3 h-3 text-yellow-500" />
                )}
                <span>{member.profile?.full_name || member.profile?.email || "Unknown"}</span>
              </div>
            ))}
          </div>
        </div>

        <Button
          variant="outline"
          size="sm"
          onClick={leaveTeam}
          className="w-full text-destructive hover:text-destructive"
        >
          <LogOut className="w-4 h-4 mr-2" />
          {team.created_by === user?.id ? "Disband Team" : "Leave Team"}
        </Button>
      </CardContent>
    </Card>
  );
};
