import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";

interface TutorCommunity {
  id: string;
  tutor_id: string;
  name: string;
  description: string | null;
  invite_code: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

interface CommunityMember {
  id: string;
  user_id: string;
  joined_at: string;
  profile?: {
    full_name: string | null;
    profile_image_url: string | null;
  };
}

interface SharedQuiz {
  id: string;
  quiz_id: string;
  shared_at: string;
  message: string | null;
  quiz?: {
    id: string;
    title: string;
    description: string | null;
    duration_minutes: number;
    question_count: number;
    is_premium: boolean;
    token_cost: number;
    is_simulation: boolean;
    course?: {
      code: string;
      name: string;
    };
  };
}

export const useTutorCommunity = () => {
  const { user } = useAuth();
  const [community, setCommunity] = useState<TutorCommunity | null>(null);
  const [members, setMembers] = useState<CommunityMember[]>([]);
  const [sharedQuizzes, setSharedQuizzes] = useState<SharedQuiz[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const fetchCommunity = async () => {
    if (!user) return;

    try {
      const { data, error } = await supabase
        .from("tutor_communities")
        .select("*")
        .eq("tutor_id", user.id)
        .maybeSingle();

      if (error) throw error;
      setCommunity(data);

      if (data) {
        // Fetch members
        const { data: membersData } = await supabase
          .from("community_members")
          .select("id, user_id, joined_at")
          .eq("community_id", data.id)
          .order("joined_at", { ascending: false });

        if (membersData && membersData.length > 0) {
          const userIds = membersData.map((m) => m.user_id);
          const { data: profiles } = await supabase
            .from("profiles")
            .select("id, full_name, profile_image_url")
            .in("id", userIds);

          const profileMap = new Map(profiles?.map((p) => [p.id, p]) || []);
          
          setMembers(
            membersData.map((m) => ({
              ...m,
              profile: profileMap.get(m.user_id) || undefined,
            }))
          );
        } else {
          setMembers([]);
        }

        // Fetch shared quizzes
        const { data: sharedData } = await supabase
          .from("community_shared_quizzes")
          .select("id, quiz_id, shared_at, message")
          .eq("community_id", data.id)
          .order("shared_at", { ascending: false });

        if (sharedData && sharedData.length > 0) {
          const quizIds = sharedData.map((s) => s.quiz_id);
          const { data: quizzes } = await supabase
            .from("quizzes")
            .select("id, title, description, duration_minutes, question_count, is_premium, token_cost, is_simulation, courses(code, name)")
            .in("id", quizIds);

          const quizMap = new Map(
            quizzes?.map((q) => [q.id, { ...q, course: q.courses as { code: string; name: string } }]) || []
          );

          setSharedQuizzes(
            sharedData.map((s) => ({
              ...s,
              quiz: quizMap.get(s.quiz_id) || undefined,
            }))
          );
        } else {
          setSharedQuizzes([]);
        }
      }
    } catch (error) {
      console.error("Error fetching community:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const createCommunity = async (name: string, description?: string) => {
    if (!user) return null;

    try {
      const { data, error } = await supabase
        .from("tutor_communities")
        .insert({
          tutor_id: user.id,
          name,
          description: description || null,
          invite_code: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      
      setCommunity(data);
      toast.success("Community created successfully!");
      return data;
    } catch (error: any) {
      console.error("Error creating community:", error);
      toast.error(error.message || "Failed to create community");
      return null;
    }
  };

  const updateCommunity = async (name: string, description?: string) => {
    if (!user || !community) return false;

    try {
      const { error } = await supabase
        .from("tutor_communities")
        .update({
          name,
          description: description || null,
          updated_at: new Date().toISOString(),
        })
        .eq("id", community.id);

      if (error) throw error;
      
      setCommunity({ ...community, name, description: description || null });
      toast.success("Community updated successfully!");
      return true;
    } catch (error: any) {
      console.error("Error updating community:", error);
      toast.error(error.message || "Failed to update community");
      return false;
    }
  };

  const shareQuiz = async (quizId: string, message?: string) => {
    if (!community) return false;

    try {
      const { data, error } = await supabase
        .from("community_shared_quizzes")
        .insert({
          community_id: community.id,
          quiz_id: quizId,
          message: message || null,
        })
        .select()
        .single();

      if (error) {
        if (error.code === "23505") {
          toast.error("Quiz already shared to community");
          return false;
        }
        throw error;
      }

      toast.success("Quiz shared to community!");
      await fetchCommunity();
      return true;
    } catch (error: any) {
      console.error("Error sharing quiz:", error);
      toast.error(error.message || "Failed to share quiz");
      return false;
    }
  };

  const unshareQuiz = async (sharedQuizId: string) => {
    try {
      const { error } = await supabase
        .from("community_shared_quizzes")
        .delete()
        .eq("id", sharedQuizId);

      if (error) throw error;
      
      setSharedQuizzes((prev) => prev.filter((s) => s.id !== sharedQuizId));
      toast.success("Quiz removed from community");
      return true;
    } catch (error: any) {
      console.error("Error removing shared quiz:", error);
      toast.error(error.message || "Failed to remove quiz");
      return false;
    }
  };

  useEffect(() => {
    fetchCommunity();
  }, [user]);

  return {
    community,
    members,
    sharedQuizzes,
    isLoading,
    createCommunity,
    updateCommunity,
    shareQuiz,
    unshareQuiz,
    refetch: fetchCommunity,
  };
};

// Hook for students to view/join communities
export const useStudentCommunity = (communityId?: string) => {
  const { user } = useAuth();
  const [communities, setCommunities] = useState<(TutorCommunity & { tutor?: { full_name: string | null; profile_image_url: string | null } })[]>([]);
  const [currentCommunity, setCurrentCommunity] = useState<TutorCommunity | null>(null);
  const [sharedQuizzes, setSharedQuizzes] = useState<SharedQuiz[]>([]);
  const [isMember, setIsMember] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  const fetchJoinedCommunities = async () => {
    if (!user) return;

    try {
      const { data: memberData } = await supabase
        .from("community_members")
        .select("community_id")
        .eq("user_id", user.id);

      if (memberData && memberData.length > 0) {
        const communityIds = memberData.map((m) => m.community_id);
        
        const { data: communitiesData } = await supabase
          .from("tutor_communities")
          .select("*")
          .in("id", communityIds)
          .eq("is_active", true);

        if (communitiesData) {
          const tutorIds = communitiesData.map((c) => c.tutor_id);
          const { data: profiles } = await supabase
            .from("profiles")
            .select("id, full_name, profile_image_url")
            .in("id", tutorIds);

          const profileMap = new Map(profiles?.map((p) => [p.id, p]) || []);
          
          setCommunities(
            communitiesData.map((c) => ({
              ...c,
              tutor: profileMap.get(c.tutor_id) || undefined,
            }))
          );
        }
      } else {
        setCommunities([]);
      }
    } catch (error) {
      console.error("Error fetching joined communities:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const fetchCommunityDetails = async (id: string) => {
    if (!user) return;

    try {
      const { data: communityData } = await supabase
        .from("tutor_communities")
        .select("*")
        .eq("id", id)
        .eq("is_active", true)
        .maybeSingle();

      setCurrentCommunity(communityData);

      if (communityData) {
        // Check membership
        const { data: memberCheck } = await supabase
          .from("community_members")
          .select("id")
          .eq("community_id", id)
          .eq("user_id", user.id)
          .maybeSingle();

        setIsMember(!!memberCheck);

        // Fetch shared quizzes if member
        if (memberCheck) {
          const { data: sharedData } = await supabase
            .from("community_shared_quizzes")
            .select("id, quiz_id, shared_at, message")
            .eq("community_id", id)
            .order("shared_at", { ascending: false });

          if (sharedData && sharedData.length > 0) {
            const quizIds = sharedData.map((s) => s.quiz_id);
            const { data: quizzes } = await supabase
              .from("quizzes")
              .select("id, title, description, duration_minutes, question_count, is_premium, token_cost, is_simulation, courses(code, name)")
              .in("id", quizIds);

            const quizMap = new Map(
              quizzes?.map((q) => [q.id, { ...q, course: q.courses as { code: string; name: string } }]) || []
            );

            setSharedQuizzes(
              sharedData.map((s) => ({
                ...s,
                quiz: quizMap.get(s.quiz_id) || undefined,
              }))
            );
          }
        }
      }
    } catch (error) {
      console.error("Error fetching community details:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const joinCommunity = async (inviteCode: string) => {
    if (!user) {
      toast.error("Please sign in to join a community");
      return false;
    }

    try {
      // Find community by invite code
      const { data: communityData, error: findError } = await supabase
        .from("tutor_communities")
        .select("id")
        .eq("invite_code", inviteCode.toUpperCase())
        .eq("is_active", true)
        .maybeSingle();

      if (findError) throw findError;
      if (!communityData) {
        toast.error("Invalid invite code");
        return false;
      }

      // Join the community
      const { error } = await supabase
        .from("community_members")
        .insert({
          community_id: communityData.id,
          user_id: user.id,
        });

      if (error) {
        if (error.code === "23505") {
          toast.error("You're already a member of this community");
          return false;
        }
        throw error;
      }

      toast.success("Successfully joined community!");
      await fetchJoinedCommunities();
      return true;
    } catch (error: any) {
      console.error("Error joining community:", error);
      toast.error(error.message || "Failed to join community");
      return false;
    }
  };

  const leaveCommunity = async (communityId: string) => {
    if (!user) return false;

    try {
      const { error } = await supabase
        .from("community_members")
        .delete()
        .eq("community_id", communityId)
        .eq("user_id", user.id);

      if (error) throw error;

      toast.success("Left community");
      setCommunities((prev) => prev.filter((c) => c.id !== communityId));
      setIsMember(false);
      return true;
    } catch (error: any) {
      console.error("Error leaving community:", error);
      toast.error(error.message || "Failed to leave community");
      return false;
    }
  };

  useEffect(() => {
    if (communityId) {
      fetchCommunityDetails(communityId);
    } else {
      fetchJoinedCommunities();
    }
  }, [user, communityId]);

  return {
    communities,
    currentCommunity,
    sharedQuizzes,
    isMember,
    isLoading,
    joinCommunity,
    leaveCommunity,
    refetch: communityId ? () => fetchCommunityDetails(communityId) : fetchJoinedCommunities,
  };
};
